services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    ports:
        - 5001:5001
    volumes:
      - ..:/workspaces/webtech
    # Crashes the codespace. 
    #command: /bin/bash -c "pip install -r requirements.txt"
